### ISSUE TITLE
blnet_web.py does not log_in

### ISSUE THREAD

**Issue by henfri** [nielstron/pyblnet#6] opened 2018-12-02 14:51 UTC
Hello,

thanks for writing pyblnet.

I tried to run the example, but it fails.

First, I had to change line 37 and following of blnet.py to:
`        if use_ta:
            host = urlparse(address).hostname
            if host==None:
              host=self.address
            self.blnet_direct = BLNETDirect(host, ta_port)`

because host was always None for me.

But then, blnet_web.py fails logging in. This is because r.headers does not include 'Set-Cookie'. 
"r" includes the BL-Net website though.

Some more debugging:
If I run with use_web=False I do get the results of blnet.fetch()

Do you have an Idea what the reason could be?

By the way: If I use the webinerface in the browser I do not have to log in. I can log in though. Here, it accepts any password.

Greetings,
Hendrik

**Comment by nielstron** [comment] 2018-12-02 21:33
The first error was likely caused by [urlparse](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse) only parsing urls correctly that are prefixed by a "//". This is not necessary and will be fixed in a similar approach to your proposal.

> But then, blnet_web.py fails logging in. This is because r.headers does not include 'Set-Cookie'.
"r" includes the BL-Net website though.
> By the way: If I use the webinerface in the browser I do not have to log in. I can log in though. Here, it accepts any password.

So as a usual guest user, anybody could read and write your in and outputs? Then, a successful login would really not signify a successful command. Do you have a proposal on how to check a successful action? Do you think an additional parameter to enable/disable logging in and respective checks would solve the problem?

> Some more debugging:
> If I run with use_web=False I do get the results of blnet.fetch()

Did you enable `use_ta`? BLNETweb data collection should not at all be activated with `use_web=False`. The result with both enabled should be a dictionary with the correct subsections, but all of them empty.

**Closed** 2018-12-09 15:42 UTC
